config/routes.rb
Rails.application.routes.draw do

  scope '/api' do

    get 'me', to: "users#show"

    devise_for :users,
      controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        confirmations: 'users/confirmations'
      }

    namespace :nba_pool do
      resources :players, only: [:index, :show]
      resources :nba_api, only: :index
    end
    
    resources :user_teams, only: [:index]
    resources :leagues, except: [:new, :edit] do
      get 'members', to: "leagues#members"
      resources :league_memberships, except: [:new, :edit]
      resources :trade_machines, except: [:new, :edit]
      resources :trades, except: [:new, :edit]
      resources :seasons, except: [:new, :edit] do
        resources :draft_picks, except: [:new, :edit]
      end
      get 'user_options', to: "teams#user_options"
      resources :teams, except: [:new, :edit] do
        resources :team_seasons, except: [:new, :edit]
        get 'roster', to: "teams#roster"
      end
      resources :players, except: [:new, :edit] do
        resources :salaries, except: [:new, :edit]
      end
    end
  
  end

  root 'homepage#index'
  get '/*path' => 'homepage#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/team_season.rb
class TeamSeason < ApplicationRecord
    belongs_to :team
    belongs_to :season, optional: true

    def year
      self.season.start_year
    end

    def roster_size
      self.team.players.count
    end

    def soft_cap_room
      self.season.base_cap - self.team.salaries.where(season_id: self.season_id).sum(&:value)
    end

    def hard_cap_room
      self.season.base_cap + 10 - self.team.salaries.where(season_id: self.season_id).sum(&:value)
    end

    def max_RFA_bid
      self.hard_cap_room
    end

    def max_UFA_bid
      self.soft_cap_room
    end

    def incoming_picks
      self.team.draft_picks.where(season_id: self.season.id).count
    end

    def dead_cap
      self.team.salaries.where(season_id: self.season_id).where(waived: true).sum(&:value)
    end

end

app/controllers/team_seasons_controller.rb
class TeamSeasonsController < ApplicationController
  before_action :set_team_season, only: %i[ show edit update destroy ]
  before_action :set_team
  before_action :authenticate_league_admin, only: %i[ new create edit update destroy ]

  # GET /team_seasons or /team_seasons.json
  def index
    @team_seasons = @team.team_seasons#.as_json(include: [:season, :team])
    res = []
    @team_seasons.each do |ts|
      t = ts.as_json(:include => [:season, :team])
      t['roster_size'] = ts.roster_size
      t['soft_cap_room'] = ts.soft_cap_room
      t['hard_cap_room'] = ts.hard_cap_room
      t['max_RFA_bid'] = ts.max_RFA_bid
      t['max_UFA_bid'] = ts.max_UFA_bid
      t['incoming_picks'] = ts.incoming_picks
      t['dead_cap'] = ts.dead_cap
      res << t
    end
    render json: res
  end

  # GET /team_seasons/1 or /team_seasons/1.json
  def show
    t = @team_season.as_json(:include => [:season, :team])
    t['roster_size'] = @team_season.roster_size
    t['soft_cap_room'] = @team_season.soft_cap_room
    t['hard_cap_room'] = @team_season.hard_cap_room
    t['max_RFA_bid'] = @team_season.max_RFA_bid
    t['max_UFA_bid'] = @team_season.max_UFA_bid
    t['incoming_picks'] = @team_season.incoming_picks
    t['dead_cap'] = @team_season.dead_cap
    render json: t
  end

  # GET /team_seasons/new
  def new
  end

  # GET /team_seasons/1/edit
  def edit
  end

  # POST /team_seasons or /team_seasons.json
  def create
    @team_season = @team.team_seasons.new(team_season_params)

    if @team_season.save
      render json: @team_season, status: :created
    else
      render json: @team_season.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /team_seasons/1 or /team_seasons/1.json
  def update
    if @team_season.update(team_season_params)
      render json: @team_season, status: :ok
    else
      render json: @team_season.errors, status: :unprocessable_entity
    end
  end

  # DELETE /team_seasons/1 or /team_seasons/1.json
  def destroy
    @team_season.destroy

    head :no_content
  end

  private
    # Use callbacks to share common setup or cosnstraints between actions.
    #
    def set_team
      @team = Team.find(params[:team_id])
    end

    def set_team_season
      @team_season = TeamSeason.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def team_season_params
      params.require(:team_season).permit(:season_id)
    end
end

app/helpers/team_seasons_helper.rb
module TeamSeasonsHelper
end

app/views/team_seasons/_form.html.erb
<%= form_with model: [@league, @team, team_season] do |form| %>
  <% if team_season.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(team_season.errors.count, "error") %> prohibited this team_season from being saved:</h2>

      <ul>
        <% team_season.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :season_id, style: "display: block"%>
    <%= form.collection_select :season_id, @team.league.seasons, :id, :start_year %>
    
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/team_seasons/_team_season.html.erb
<div id="<%= dom_id team_season %>">
  <p>
    <strong>Team:</strong>
    <%= team_season.team.name %>
  </p>

  <p>
    <strong>Season:</strong>
    <%= team_season.year %>
  </p>


</div>

app/views/team_seasons/edit.html.erb
<h1>Editing team season</h1>

<%= render "form", team_season: @team_season %>

<br>

<div>
  <%= link_to "Show this team season", @team_season %> |
  <%= link_to "Back to team seasons", team_seasons_path %>
</div>

app/views/team_seasons/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Team seasons</h1>

<%= @team.name %>

<div id="team_seasons">
  <% @team_seasons.each do |team_season| %>
    <%= render team_season %>
    <p>
      <%= link_to "Show this team season", league_team_team_season_path(@league, @team, team_season) %>
    </p>
  <% end %>
</div>

<%= link_to "New team season", new_league_team_team_season_path %>

app/views/team_seasons/new.html.erb
<h1>New team season</h1>

<%= render "form", team_season: @team_season %>

<br>

<div>
  <%= link_to "Back to team seasons", league_team_team_seasons_path %>
</div>

app/views/team_seasons/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @team_season %>

<div>
  <%= link_to "Edit this team season", edit_league_team_team_season_path(@league, @team, @team_season) %> |
  <%= link_to "Back to team seasons", league_team_team_seasons_path %>

  <%= button_to "Destroy this team season", league_team_team_season_path(@league, @team, @team_season), method: :delete %>
</div>