config/routes.rb
Rails.application.routes.draw do

  scope '/api' do

    get 'me', to: "users#show"

    devise_for :users,
      controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        confirmations: 'users/confirmations'
      }

    namespace :nba_pool do
      resources :players, only: [:index, :show]
      resources :nba_api, only: :index
    end
    
    resources :user_teams, only: [:index]
    resources :leagues, except: [:new, :edit] do
      get 'members', to: "leagues#members"
      resources :league_memberships, except: [:new, :edit]
      resources :trade_machines, except: [:new, :edit]
      resources :trades, except: [:new, :edit]
      resources :seasons, except: [:new, :edit] do
        resources :draft_picks, except: [:new, :edit]
      end
      get 'user_options', to: "teams#user_options"
      resources :teams, except: [:new, :edit] do
        resources :team_seasons, except: [:new, :edit]
        get 'roster', to: "teams#roster"
      end
      resources :players, except: [:new, :edit] do
        resources :salaries, except: [:new, :edit]
      end
    end
  
  end

  root 'homepage#index'
  get '/*path' => 'homepage#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/draft_pick.rb
class DraftPick < ApplicationRecord
    belongs_to :team
    belongs_to :original_owner, class_name: "Team", foreign_key: :original_owner_id
    belongs_to :season

    before_validation :set_team_to_original_owner

    private

    def set_team_to_original_owner
      self.team_id = self.original_owner_id
    end
end

app/models/league.rb
class League < ApplicationRecord
    belongs_to :user, :inverse_of => :owned_leagues
    has_many :teams, dependent: :destroy
    has_many :league_memberships, dependent: :destroy
    has_many :members, through: :league_memberships, class_name: "User"
    has_many :trades, dependent: :destroy
    has_many :seasons, dependent: :destroy
    has_many :players, dependent: :destroy

    accepts_nested_attributes_for :seasons
    accepts_nested_attributes_for :league_memberships

    after_create :create_admin_membership

    def admins
      self.league_memberships
      .where(role: "admin")
      .map(&:member)
    end

    private

    def create_admin_membership
      LeagueMembership.create!(member_id: self.user_id, league_id: self.id, role: "admin")
    end

end

app/models/league_membership.rb
class LeagueMembership < ApplicationRecord
  belongs_to :member, class_name: "User"
  belongs_to :league
end

app/models/nba_pool.rb
module NbaPool
  def self.table_name_prefix
    "nba_pool_"
  end
end

app/models/player.rb
class Player < ApplicationRecord
    belongs_to :team, optional: true
    belongs_to :league
    has_many :salaries, dependent: :destroy
    validate :player_exists_in_nba, :on => :create
    validates :nba_id, uniqueness: { scope: :league }

    accepts_nested_attributes_for :salaries

    private

    def player_exists_in_nba
      errors.add(:player, "has to be in the NBA") unless NbaPool::Player.exists?(nba_id: self.nba_id)
    end
end

app/models/salary.rb
class Salary < ApplicationRecord
    belongs_to :player
    belongs_to :season, optional: true
end

app/models/season.rb
class Season < ApplicationRecord
  belongs_to :league
  has_many :team_seasons, dependent: :destroy
  has_many :draft_picks
  has_many :trades
  has_many :salaries

  accepts_nested_attributes_for :team_seasons
end

app/models/team.rb
class Team < ApplicationRecord
    belongs_to :league
    has_many :user_teams, dependent: :destroy
    has_many :users, through: :user_teams
    has_many :team_seasons, dependent: :destroy
    has_many :trade_proposals, :inverse_of => :team1, class_name: "Trade", foreign_key: :team1_id
    has_many :received_trade_proposals, :inverse_of => :team2, class_name: "Trade", foreign_key: :team2_id
    has_many :players
    has_many :draft_picks
    has_many :original_draft_picks, :inverse_of => :original_owner, class_name: "DraftPick", foreign_key: :original_owner_id
    has_many :salaries, through: :players

    accepts_nested_attributes_for :players
    accepts_nested_attributes_for :user_teams
    accepts_nested_attributes_for :team_seasons
    accepts_nested_attributes_for :draft_picks

end

app/models/team_season.rb
class TeamSeason < ApplicationRecord
    belongs_to :team
    belongs_to :season, optional: true

    def year
      self.season.start_year
    end

    def roster_size
      self.team.players.count
    end

    def soft_cap_room
      self.season.base_cap - self.team.salaries.where(season_id: self.season_id).sum(&:value)
    end

    def hard_cap_room
      self.season.base_cap + 10 - self.team.salaries.where(season_id: self.season_id).sum(&:value)
    end

    def max_RFA_bid
      self.hard_cap_room
    end

    def max_UFA_bid
      self.soft_cap_room
    end

    def incoming_picks
      self.team.draft_picks.where(season_id: self.season.id).count
    end

    def dead_cap
      self.team.salaries.where(season_id: self.season_id).where(waived: true).sum(&:value)
    end

end

app/models/trade.rb
class Trade < ApplicationRecord
  belongs_to :team1, class_name: "Team", foreign_key: :team1_id
  belongs_to :team2, class_name: "Team", foreign_key: :team1_id
  belongs_to :season, optional: true
  belongs_to :league

  after_create :set_status

  def set_status
    self.update(status: "pending")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  has_many :league_memberships, foreign_key: :member_id
  has_many :owned_leagues, class_name: "League"
  has_many :leagues, through: :league_memberships, class_name: "League", foreign_key: :member_id
  has_many :user_teams
  has_many :teams, through: :user_teams
  has_many :players, through: :teams
  has_many :trade_proposals, through: :teams
  has_many :received_trade_proposals, through: :teams

  accepts_nested_attributes_for :league_memberships
  accepts_nested_attributes_for :user_teams
  accepts_nested_attributes_for :teams

end

app/models/user_team.rb
class UserTeam < ApplicationRecord
  belongs_to :user
  belongs_to :team
end

app/controllers/salaries_controller.rb
class SalariesController < ApplicationController
  before_action :set_league
  before_action :set_player
  before_action :set_salary, only: %i[ show edit update destroy ]
  before_action :authenticate_league_admin, only: %i[ new create edit update destroy ]

  # GET /salaries or /salaries.json
  def index
    @salaries = @player.salaries
    render json: @salaries.as_json(include: [:player, :season])
  end

  # GET /salaries/1 or /salaries/1.json
  def show
    render json: @salary.as_json(include: [:player, :season])
  end

  # GET /salaries/new
  def new
  end

  # GET /salaries/1/edit
  def edit
  end

  # POST /salaries or /salaries.json
  def create
    @salary = @player.salaries.new(salary_params)

    if @salary.save
      render json: @salary, status: :created
    else
      render json: @salary.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /salaries/1 or /salaries/1.json
  def update
    if @salary.update(salary_params)
      render json: @salary, status: :ok
    else
      render json: @salary.errors, status: :unprocessable_entity
    end
  end

  # DELETE /salaries/1 or /salaries/1.json
  def destroy
    @salary.destroy

    head :no_content
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # 

    def set_player
      @player = Player.find(params[:player_id])
    end

    def set_salary
      @salary = Salary.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def salary_params
      params.require(:salary).permit(:season_id, :value, :free_agent, :waiver_acquisition, :waived)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/draft_picks_helper.rb
module DraftPicksHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/salaries_helper.rb
module SalariesHelper
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/helpers/user_teams_helper.rb
module UserTeamsHelper
end

app/views/salaries/_form.html.erb
<%= form_with model: [@league, @player, salary] do |form| %>
  <% if salary.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(salary.errors.count, "error") %> prohibited this salary from being saved:</h2>

      <ul>
        <% salary.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :season_id, style: "display: block" %>
    <%= form.collection_select :season_id, @league.seasons, :id, :start_year, include_blank: true  %>
  </div>

  <div>
    <%= form.label :value, style: "display: block" %>
    <%= form.number_field :value %>
  </div>

  <div>
    <%= form.label :free_agent, style: "display: block" %>
    <%= form.check_box :free_agent %>
  </div>

  <div>
    <%= form.label :waiver_acquisition, style: "display: block" %>
    <%= form.check_box :waiver_acquisition %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/salaries/_salary.html.erb
<div id="<%= dom_id salary %>">
  <p>
    <strong>Season:</strong>
    <%= salary.season.start_year %>
  </p>

  <p>
    <strong>Value:</strong>
    <%= salary.value %>
  </p>

  <p>
    <strong>Free agent:</strong>
    <%= salary.free_agent %>
  </p>

  <p>
    <strong>Waiver acquisition:</strong>
    <%= salary.waiver_acquisition %>
  </p>

</div>

app/views/salaries/edit.html.erb
<h1>Editing salary</h1>

<%= render "form", salary: @salary %>

<br>

<div>
  <%= link_to "Show this salary", league_player_salary_path(@league, @player, @salary) %> |
  <%= link_to "Back to salaries", league_player_salaries_path(@league, @player) %>
</div>

app/views/salaries/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Salaries</h1>

<div id="salaries">
  <% @salaries.each do |salary| %>
    <%= render salary %>
    <p>
      <%= link_to "Show this salary", league_player_salary_path(@league, @player, salary) %>
    </p>
  <% end %>
</div>

<%= link_to "New salary", new_league_player_salary_path(@league, @player) %>

app/views/salaries/new.html.erb
<h1>New salary</h1>

<%= render "form", salary: @salary %>

<br>

<div>
  <%= link_to "Back to salaries", league_player_salaries_path(@league, @player) %>
</div>

app/views/salaries/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @salary %>

<div>
  <%= link_to "Edit this salary", edit_league_player_salary_path(@league, @player, @salary) %> |
  <%= link_to "Back to salaries", league_player_salaries_path(@league, @player) %>

  <%= button_to "Destroy this salary", league_player_salary_path(@league, @player, @salary), method: :delete %>
</div>