config/routes.rb
Rails.application.routes.draw do

  scope '/api' do

    get 'me', to: "users#show"

    devise_for :users,
      controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        confirmations: 'users/confirmations'
      }

    namespace :nba_pool do
      resources :players, only: [:index, :show]
      resources :nba_api, only: :index
    end
    
    resources :user_teams, only: [:index]
    resources :leagues, except: [:new, :edit] do
      get 'members', to: "leagues#members"
      resources :league_memberships, except: [:new, :edit]
      resources :trade_machines, except: [:new, :edit]
      resources :trades, except: [:new, :edit]
      resources :seasons, except: [:new, :edit] do
        resources :draft_picks, except: [:new, :edit]
      end
      get 'user_options', to: "teams#user_options"
      resources :teams, except: [:new, :edit] do
        resources :team_seasons, except: [:new, :edit]
        get 'roster', to: "teams#roster"
      end
      resources :players, except: [:new, :edit] do
        resources :salaries, except: [:new, :edit]
      end
    end
  
  end

  root 'homepage#index'
  get '/*path' => 'homepage#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/nba_pool.rb
module NbaPool
  def self.table_name_prefix
    "nba_pool_"
  end
end

app/models/nba_pool/player.rb
class NbaPool::Player < ApplicationRecord
  validates :nba_id, uniqueness: true
end

app/models/player.rb
class Player < ApplicationRecord
    belongs_to :team, optional: true
    belongs_to :league
    has_many :salaries, dependent: :destroy
    validate :player_exists_in_nba, :on => :create
    validates :nba_id, uniqueness: { scope: :league }

    accepts_nested_attributes_for :salaries

    private

    def player_exists_in_nba
      errors.add(:player, "has to be in the NBA") unless NbaPool::Player.exists?(nba_id: self.nba_id)
    end
end

app/controllers/nba_pool/nba_api_controller.rb
class NbaPool::NbaApiController < ApplicationController
  before_action :set_nba_pool_player, only: %i[ show edit update destroy ]
  skip_before_action :authenticate_league_admin
  skip_before_action :set_league
  include NBAPlayerAPI

  def index
    players_from_api = NBAPlayerAPI.get_player_data("#{Time.now.year}-#{(Time.now.year + 1).to_s[-2..-1]}")
    players_from_api.each do |player|
      new_player = NbaPool::Player.find_or_create_by(nba_id: player.nba_id)
      new_player.update!(
        first_name: player.first_name,
        last_name: player.last_name,
        position: player.position,
        slug: player.slug,
        draft_year: player.drafted_year,
        nba_team: player.current_team
      )
    end
    render json: { message: "Successfully fetched NBA Player data on #{Date.today.to_s}", status: :ok}
  end
end

app/controllers/nba_pool/players_controller.rb
class NbaPool::PlayersController < ApplicationController
  before_action :set_nba_pool_player, only: %i[ show edit update destroy ]
  skip_before_action :authenticate_league_admin
  skip_before_action :set_league
  skip_before_action :authenticate_user!, only: %i[ index show ]

  # GET /nba_pool/players or /nba_pool/players.json
  def index
    @nba_pool_players = NbaPool::Player.all
    render json: @nba_pool_players
  end

  # GET /nba_pool/players/1 or /nba_pool/players/1.json
  def show
    render json: @nba_pool_player
  end

  # GET /nba_pool/players/new
  def new
  end

  # GET /nba_pool/players/1/edit
  def edit
  end

  # POST /nba_pool/players or /nba_pool/players.json
  def create
  end

  # PATCH/PUT /nba_pool/players/1 or /nba_pool/players/1.json
  def update
  end

  # DELETE /nba_pool/players/1 or /nba_pool/players/1.json
  def destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nba_pool_player
      @nba_pool_player = NbaPool::Player.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def nba_pool_player_params
      params.require(:nba_pool_player).permit(:first_name, :last_name, :position, :nba_id, :slug, :draft_year, :nba_team)
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: %i[ show edit update destroy ]
  before_action :authenticate_league_admin, only: %i[ new create edit update destroy ]

  # GET /players or /players.json
  def index
    @players = @league.players
    render json: @players.as_json(include: [:team, :salaries])
  end

  # GET /players/1 or /players/1.json
  def show
    render json: @player.as_json(include: [:team, {salaries: { include: [:season, :player]}}])
  end

  # GET /players/new
  def new
    
    #@team = request&.referrer&.match?("/roster") ? request.referrer.split("/")[-2] : nil

  end

  # GET /players/1/edit
  def edit
  end

  # POST /players or /players.json
  def create
    if !params[:nba_player_id]
      render json: {message: "You can only add an existing NBA player", status: :unprocessable_entity }
      return
    else
      @nba_player = NbaPool::Player.find_by(nba_id: params[:nba_player_id])
      @player = @league.players.find_or_initialize_by(nba_id: params[:nba_player_id])
      @player.assign_attributes(
        first_name: @nba_player&.first_name,
        last_name: @nba_player&.last_name,
        position: @nba_player&.position,
        slug: @nba_player&.slug,
        draft_year: @nba_player&.draft_year,
        nba_team: @nba_player&.nba_team,
        team_id: params[:team_id]
      )
    end

    if @player.save
      render json: @player, status: :created
    else
      render json: @player.errors, status: :unprocessable_entity
    end

  end

  # PATCH/PUT /players/1 or /players/1.json
  def update
    if @player.update(player_params)
      render json: @player
    else
      render json: @player.errors, status: :unprocessable_entity
    end
  end

  # DELETE /players/1 or /players/1.json
  def destroy
    @player.destroy

    head :no_content
  end

  private
    # Use callbacks to share common setup or constraints between actions

    def set_player
      @player = Player.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def player_params
      params.require(:player).permit(:first_name, :team_id, :last_name, :position, :nba_id, :slug, :draft_year, :trade_block)
    end
end

app/helpers/nba_pool/nba_api_helper.rb
module NbaPool::NbaApiHelper
end

app/helpers/nba_pool/players_helper.rb
module NbaPool::PlayersHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/nba_pool/players/_form.html.erb
<%= form_with(model: nba_pool_player) do |form| %>
  <% if nba_pool_player.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(nba_pool_player.errors.count, "error") %> prohibited this nba_pool_player from being saved:</h2>

      <ul>
        <% nba_pool_player.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :position, style: "display: block" %>
    <%= form.text_field :position %>
  </div>

  <div>
    <%= form.label :nba_id, style: "display: block" %>
    <%= form.number_field :nba_id %>
  </div>

  <div>
    <%= form.label :slug, style: "display: block" %>
    <%= form.text_field :slug %>
  </div>

  <div>
    <%= form.label :draft_year, style: "display: block" %>
    <%= form.number_field :draft_year %>
  </div>

  <div>
    <%= form.label :nba_team, style: "display: block" %>
    <%= form.text_field :nba_team %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/nba_pool/players/_player.html.erb
<div class="listing" id="<%= dom_id player %>">
  <p>
    <%= player.first_name %>
  </p>

  <p>
    <%= player.last_name %>
  </p>

  <p>
    <%= player.position %>
  </p>

  <p>
    <%= player.draft_year %>
  </p>

  <p>
    <%= player.nba_team %>
  </p>

</div>

app/views/nba_pool/players/edit.html.erb
<h1>Editing player</h1>

<%= render "form", nba_pool_player: @nba_pool_player %>

<br>

<div>
  <%= link_to "Show this player", @nba_pool_player %> |
  <%= link_to "Back to players", nba_pool_players_path %>
</div>

app/views/nba_pool/players/index.html.erb
<p style="color: green"><%= notice %></p>

<%= button_to "Get NBA Players", nba_pool_nba_api_index_path, method: 'get' %>

<h1>Players</h1>

<div id="nba_pool_players">
  <div class="listing">
    <p>
      <strong>First name</strong>
    </p>

    <p>
      <strong>Last name</strong>
    </p>

    <p>
      <strong>Position</strong>
    </p>

    <p>
      <strong>Draft year</strong>
    </p>

    <p>
      <strong>Nba team</strong>
    </p>
  </div>
  <% @nba_pool_players.each do |nba_pool_player| %>
    
        <%= render nba_pool_player %>
        <p>
          <%= link_to "Show this player", nba_pool_player %>
        </p>
      <% end %>
    </div>

<%= link_to "New player", new_nba_pool_player_path %>

app/views/nba_pool/players/new.html.erb
<h1>New player</h1>

<%= render "form", nba_pool_player: @nba_pool_player %>

<br>

<div>
  <%= link_to "Back to players", nba_pool_players_path %>
</div>

app/views/nba_pool/players/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @nba_pool_player %>

<div>
  <%= link_to "Edit this player", edit_nba_pool_player_path(@nba_pool_player) %> |
  <%= link_to "Back to players", nba_pool_players_path %>

  <%= button_to "Destroy this player", @nba_pool_player, method: :delete %>
</div>